### ISSUE TITLE
Support Map Fragment is null if setContentView is not called

### ISSUE THREAD

**Issue by abhiank** [CraZyLegenD/Set-Of-Useful-Kotlin-Extensions-and-Helpers#15]
Thanks for this library. I just integrated it into an activity with a map. 

```
private val binding: GoogleMapSettingActivityBinding by viewBinding(GoogleMapSettingActivityBinding::inflate)
```

and then in onCreate, I did not called setContentView as was mentioned in the documentation. 

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val mapFragment: SupportMapFragment? =
                supportFragmentManager.findFragmentById(R.id.map) as? SupportMapFragment
        mapFragment?.getMapAsync(this)
        ...
```

The problem here is that mapFragment is null. However, if I call setContentView(binding.root) before calling findFragmentById then mapFragment is not null, like this - 

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(v.root)
        ...
```
What could be the issue?

**Comment by abhiank** [comment]
On looking further into this, I released this is happening because the `createBinding() {}` which is annotated with `@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)` in `ActivityViewBindingDelegate` is called **after** onCreate() in the activity is done executing. 

So everything in onCreate() which expects the views to be already on the screen and rendered are not present at all. Seems like this is how lifecycle observer is supposed to work. So this way of view-binding wont work for me. setContentView needs to be called after super.onCreate and not somewhere after or in the middle of onCreate() execution. 

Is there someway this can be done?

**Comment by CraZyLegenD** [comment]
just use onPostCreate

**Comment by CraZyLegenD** [comment]
> On looking further into this, I released this is happening because the `createBinding() {}` which is annotated with `@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)` in `ActivityViewBindingDelegate` is called **after** onCreate() in the activity is done executing.
> 
> So everything in onCreate() which expects the views to be already on the screen and rendered are not present at all. Seems like this is how lifecycle observer is supposed to work. So this way of view-binding wont work for me. setContentView needs to be called after super.onCreate and not somewhere after or in the middle of onCreate() execution.
> 
> Is there someway this can be done?

Yeah I noticed the behavior, would implement another lambda method into the delegate that'll happen after setContentView

You can use by viewBinder meanwhile or onPostCreate

**Comment by CraZyLegenD** [comment]
There are few options you can use here.
1. Move your logic in onPostCreate (i think you didn't read the updated article i made an issue the first time i published it, instead of onCreate i was supposed to use onPostCreate)
2. use by viewBinder() and manually set the setContentView like you do

**Comment by CraZyLegenD** [comment]
Take a look in the updated [README](https://github.com/CraZyLegenD/Set-Of-Useful-Kotlin-Extensions-and-Helpers/blob/master/viewbinding/README.md)

**Comment by abhiank** [comment]
Option 1 is good. I'd forgotten about onPostCreate. But I'm gonna go with option 2 for now as it'll need minimum changes. Thanks.
