### ISSUE TITLE
CountUpTimer startTimer no what=MSG

### ISSUE THREAD

**Issue by yyg20101** [CraZyLegenD/Set-Of-Useful-Kotlin-Extensions-and-Helpers#6]
CountUpTimer  bug

**Comment by CraZyLegenD** [comment]
That information doesn't help, you need to provide a code snippet you've written

**Comment by yyg20101** [comment]
/**
     * Method to start the timer.
     */
    fun startTimer() {
   ...........
        handler?.obtainMessage()?.apply {
            what = MSG   //TODO
            handler?.sendMessage(this)
        }
    }

**Comment by CraZyLegenD** [comment]
The code to use the timer is

```
 val countUpTimer = object : CountUpTimer(ALLOWED_MS_OF_INACTIVITY) {
override fun onTimerTick(timeRemaining: Long) {
}
override fun onTimerFinish() {
}
}
countUpTimer.startTimer()
```
